### ISSUE TITLE
Crash on opening in macOS 10.13.6 High Sierra

### ISSUE THREAD

**Issue by metaphysician** [tahoma2d/tahoma2d#151] opened 2020-09-08 07:42 UTC
macOS version 10.13.6 (High Sierra)
GPU - Radeon Vega 56

EDIT:per the closed Issue #136  this looks like the macOS version either wasn't updated on the download server or the configuration of 10.9 as the version to be used did not get committed to the build in Xcode. i often see developers creating separate 10.15 Catalina build versions from earlier versions probably due to the increasingly stringent code signing requirements in 10.15 compared to earlier versions.

Versions Opened - 1.0.1,1.0 Beta 0.5

1.0.1 dmg downloaded and installed, gave typical warning. then when opening program it immediately crashes. subsequent openings produced same result. i have the entire stack trace but i suspect the issue is with libtoonzlib.dylib (which the error says was built for 10.15 (macOS Catalina)). the site says it should work with anything after 10.0 (El Capitan), so i hope this is just an Xcode version compilation compatibility error and not a situation where it only works with Catalina. anyway here's the error:

Process:               Tahoma [58757]
Path:                  /Applications/Tahoma.app/Contents/MacOS/Tahoma
Identifier:            io.github.turtletooth.Tahoma
Version:               1.0.1 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Tahoma [58757]
User ID:               501

Date/Time:             2020-09-08 00:24:40.524 -0700
OS Version:            Mac OS X 10.13.6 (17G9016)
Report Version:        12
Anonymous UUID:        36709800-C9D4-0938-7AD4-B97FA5701E0C

Sleep/Wake UUID:       5F5142F3-3CEA-47B5-B417-EC20FBDD8406

Time Awake Since Boot: 560000 seconds
Time Since Wake:       43000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Tahoma.app/Contents/MacOS/libtoonzlib.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

-------------------------------------------------------

thanks - hope this helps and let me know if you need any more info.

**Comment by metaphysician** [comment] 2020-09-08 07:45
Oh BTW the 1.0 beta 0.5 just gave the error that the app was corrupted and should be put in the Trash. i don't think that's a big deal but thought i'd mention it. no error onscreen but Console might have more info if you need it.

**Comment by artisteacher** [comment] 2020-09-08 11:24
You are using the release built on Sep. 4th? I did build on Catalina but with Xcode set to 10.9 deployment. It opens just fine on 10.14. Can you save the entire crash report at a .txt file & post that here?

**Comment by manongjohn** [comment] 2020-09-08 11:28
I had the same issue when I tried the initial Tahoma 1.0 release to macOS 10.13. I believe it mentioned there were 2 dylib files that were specific to 10.15 so I couldn't run it.

**Comment by manongjohn** [comment] 2020-09-08 11:32
Actually looking at the error log above, it appears it's referencing something in libSystem.B.dylib which might exist in 10.14 and above, but not 10.13 and below.

**Comment by metaphysician** [comment] 2020-09-08 11:45
hello @artisteacher - here's the complete text from the crashlog
[crashlog-10.13.6_9-4-20build.txt](https://github.com/turtletooth/tahoma/files/5188048/crashlog-10.13.6_9-4-20build.txt)

**Comment by artisteacher** [comment] 2020-09-09 16:29
I’ve found a Mac running 10.13.5 that I can use periodically & I see the same crash.

I’ve tried running some different build configurations in Xcode but it hasn’t helped so far. It looks like Xcode uses the 10.15 sdk. That’s supposed to be ok for backwards compatibility according to apple. However a lot of developers seem to prefer to use sdk’s from old versions of Xcode since it prevents our current issue.

Building without Xcode with travis-build.sh or building manually has actually been worse - the builds only open in Catalina - not even 10.14.

**Comment by manongjohn** [comment] 2020-09-09 17:23
I currently build on 10.13, but validate it runs on 10.15, so I only have to worry about forward compatibility which is probably why the scripts work well for me.  Since you are building backward compatible versions, you'd either need to figure out how to set that up in the scripts or continue to use Xcode to build.

For now, I guess, Tahoma requires a minimum macOS 10.14 to run.

I'm currently reworking my 10.13 build environment as I need to not use the brew'd opencv.  I have a locally compiled opencv and an lgpl ffmpeg but having issues with the DMG  file not containing the opencv libraries like it needs.  Still working on it.  I also don't have Canon SDKs.

**Comment by metaphysician** [comment] 2020-09-09 19:49
i see. it seems like this isn't going to get resolved in a binary build for older macOS's anytime soon, then. i do have Xcode and brew to (possibly) make builds myself ( Xcode's at version 10.1 from early 2019) but i haven't tried seeing whether that will work since you need ffmpeg and and the CanonSDK. kind of a shame, i got all excited about Tahoma being easier to deal with than OpenToonz from Darren T's Youtube Channel (vertical columns for animation don't feel intuitive to me). but i did find out that horizontal orientation of the Xsheet got into OpenToonz awhile back so maybe i'll start there and wait for Tahoma, or maybe i'll bite the bullet and upgrade the macOS to 10.14 (not Catalina though, too many older 32 bit apps and games under Wine).

**Comment by manongjohn** [comment] 2020-09-09 20:19
You can build without Canon SDK if you aren't doing any Stop Motion or if you are ok doing Stop Motion with webcam.

**Comment by artisteacher** [comment] 2020-09-09 21:25
You can also link ffmpeg manually after building which is how OpenToonz works.

I'll keep working at it but it's slow going since I don't have 10.13 at home.

**Comment by artisteacher** [comment] 2020-09-10 16:09
So good news, I found an old backup of Xcode which has the 10.13 SDK. I'll give building with it a shot.

**Comment by jeremybullock** [comment] 2020-09-10 16:13
Awesome!  Thanks.

**Comment by artisteacher** [comment] 2020-09-10 17:03
@metaphysician - please give [this build](https://drive.google.com/file/d/1GbbcqKUmX0uJ2bzU6PMnRHjZIIQLbO9Z/view?usp=sharing) a try.

**Comment by metaphysician** [comment] 2020-09-11 02:20
hi @artisteacher - looks like this one starts up fine! i was able to successfully create a project and save it but i did use the Quit option from the menu to quit the program and it gave a standard 'Unexpected Quit Error' dialog once the application closed. weirdly, the Reopen button does not reopen Tahoma, but double clicking on the app icon is fine. so i'm not sure if that's an issue or not. i did not get any crashing during the use of the program, and after the crash after close i was able to reopen Tahoma and the scene i was working on with no issues. so there you go. let me know if you need any further testing!

**Comment by artisteacher** [comment] 2020-09-11 02:33
I'm glad that worked! The crash issue sounds like #141. I usually reopen from the app icon, not the reopen button with the crash notification, so I'm unsure if that's new or not.

**Comment by artisan21** [comment] 2020-09-11 21:31
Hi. I am having trouble opening Tahoma on an older iMac myself. It is a late 2009 27" iMac with Core i7 CPU running at 2.8 GHz, 16 GB of RAM, Radeon HD 4850 GPU with 512 MB of RAM, and I run macOS High Sierra 10.13.6. I get the same issue metaphysician did. Tahoma does not start up on my computer at all. I wanted to run a compiled binary. I am not compiling Tahoma because I don't have the knowledge to do that. Is there a way to rum this program on my system? It shouldn't be outdated, because I run OpenToonz Morevna Edition on my system already. Thanks.

**Comment by jeremybullock** [comment] 2020-09-11 21:38
I am uploading a build right now that should work with 10.13.

**Comment by artisan21** [comment] 2020-09-11 21:39
Thanks. I will await that. :)

**Comment by jeremybullock** [comment] 2020-09-11 21:40
Can you try now?  I replaced the mac file in the 1.0.1 release.

**Comment by artisan21** [comment] 2020-09-11 21:44
Hi, Mr. Bullock,

If you put the file on the website to download from the link, I tried that and it didn’t start up. It crashed right away. So, what do I do? Thanks.

**Comment by jeremybullock** [comment] 2020-09-11 21:46
Hmm . . . I put a different one up just now.  Do you want to try that?

**Comment by artisan21** [comment] 2020-09-11 21:47
I will try it. Thanks.

**Comment by artisan21** [comment] 2020-09-11 22:11
My apologies. It eventually worked after all. It started up the second time I ran the most recently downloaded version of it. Thanks for the help. I will experiment with Tahoma. I think it will be a nice addition to my repertoire of drawing and animation. Thanks again. 👍

**Comment by artisteacher** [comment] 2020-09-11 23:31
For some reason, opening the first time after installing always fails - the same thing happens with OTX. Afterwards, both programs open normally.

**Comment by metaphysician** [comment] 2020-09-11 23:34
yes, i noticed that too. the crash isn't obvious (i don't get a dialog) but it only runs the second time in my experience. after that it starts up fine.

**Comment by artisteacher** [comment] 2020-09-21 21:54
Due to some changes in Xcode, I want to see if I can get Tahoma to build with the current SDK and still run on 10.13. I've made a couple test builds with slightly different settings. They both run fine on 10.14 & 10.15, but it could go either way on 10.13. 

@metaphysician & @manongjohn, if you would be willing to test them out, that would be great.

[Standard Architecture Build](https://drive.google.com/file/d/1SpE6tANdG4d7h_2wOV_n95fwTVCMu1ZH/view?usp=sharing)
[64bit Build](https://drive.google.com/file/d/18K3jOFq1wJ9jFHxSCOFULdC2oJ44_twa/view?usp=sharing)

**Comment by manongjohn** [comment] 2020-09-21 22:06
Sure. I'll check it out as soon as I can.

FYI, I am now prepared to build Tahoma completely on my 10.13 VM as I do for OTX.  I can be a backup if needed, though I build on Xcode 10.1, QT 10.15 (currently due to brew), boost 1.61

**Comment by artisteacher** [comment] 2020-09-21 22:23
Thanks! I have one more thing I can try if these both fail on 10.13, but it's good to have a backup.

**Comment by manongjohn** [comment] 2020-09-21 22:39
@artisteacher I tried both and they both crash upon opening for the same reason as the OP.

**Comment by artisteacher** [comment] 2020-09-22 00:16
Thanks. That's too bad. I can still build with 10.13, but I wonder if there's a step I'm missing to make the 10.15 sdk backwards compatible.

**Comment by artisteacher** [comment] 2020-09-22 02:56
It's actually looking like it may not be possible to use any sdk before 10.15 with Xcode 12. I'll keep looking to see if there are other settings that improve the backwards compatibility. Here's [my last attempt for today](https://drive.google.com/file/d/19W7KTSVieocTsaECxIn8hKzpOXO6kZ3I/view?usp=sharing).

**Comment by manongjohn** [comment] 2020-09-22 11:59
Unfortunately, both still crash for the same reason.

**Comment by artisteacher** [comment] 2020-09-22 20:15
I'm wondering if the problem isn't directly in Xcode. The minimum deployment target doesn't get set until after the Xcode project is created. Could it need to be set somewhere before that?

**Comment by artisteacher** [comment] 2020-09-25 12:57
I was finally able to build successfully with the 10.15sdk! It opened just fine on 10.13.6. If anyone one else wants to try it out, [here it is.](https://drive.google.com/file/d/1gUyHuij9VJl5Z0gy9cNxhLRaY2U1gKGx/view?usp=sharing)

The problem I was running into is that before generating an Xcode project, the computer automatically built everything with a 10.15 deployment target. So completing the build in Xcode with a different deployment target didn't actually work. Building just through terminal had the same issue.

This time I used tahoma_build.sh, but on line 18, I added a line to export the minimum deployment target as 10.13. 

Building with Xcode or manually in Terminal is probably fine as long as the minimum deployment target is exported after creating the build directory.

 I could probably set a lower deployment target now, but I have no way of testing a device before 10.13.

**Comment by manongjohn** [comment] 2020-09-25 13:11
Great to hear! Can you provide the exact line you added and I'll make sure it gets into the scripts with the other changes I need to make.

**Comment by artisteacher** [comment] 2020-09-25 13:30
Will do this afternoon. Thanks for updating the scripts! They save so much time.

**Comment by artisan21** [comment] 2020-09-25 16:32
It does work on 10.13.6, but I needed to start it twice to run it. It crashed the first time I opened it. No biggie, as it did run. Twice was the charm. Thanks for your efforts.

**Comment by artisteacher** [comment] 2020-09-25 20:44
@manongjohn - here you go:
`export MACOSX_DEPLOYMENT_TARGET=10.13`

@artisan21 - for some reason some portable builds on macOS need to be opened twice after downloading. Afterwards, it should open normally. OTX has the same problem. Interestingly, the Morevna release does not. I'm not sure what the difference is. If you have have a crash report to share, it could be helpful.

In console, after overriding Gatekeeper & choosing to open Tahoma for the first time (when opening fails), I get these messages:
<img width="1468" alt="Screen Shot 2020-09-25 at 4 27 36 PM" src="https://user-images.githubusercontent.com/21159116/94313165-40eb9600-ff4c-11ea-8335-be1b18641475.png">

Maybe it's a signing/notarization issue?

**Comment by artisteacher** [comment] 2020-10-01 22:47
Just an FYI - the crash on open in macOS 10.13 is fixed. The failure to open the first time after overriding Gatekeeper is an issue on macOS 10.13 - 10.15.

**Comment by artisteacher** [comment] 2020-10-10 14:42
I read somewhere that apps can fail to open on the first launch if there are no preferences set. Even though the app fails, preferences get set upon trying to open so that opening succeeds afterwards.

**Comment by manongjohn** [comment] 2021-01-27 15:23
Closing as this is similar to #339.   Tahoma2D 1.1 and future builds are built on 10.13, for now.

**Closed by manongjohn** 2021-01-27 15:23 UTC
Labels: bug, mac
