### ISSUE TITLE
Tahoma Crash(And OT)-New knowledge

### ISSUE THREAD

**Issue by Tragustauro** [tahoma2d/tahoma2d#900] opened 2022-02-06 19:20 UTC
@[manongjohn] and [artisteacher]
Hello.

Thank you for putting in time to do this. 
I have both Opentoonz and Tahoma as I am trying them both out for my productions. 

Both have issues.

I am actually not 100 sure the crashes is caused by the imported sounds. Both mp3 or wav.

I want to use the softwares primarely as Pencil line tests. And I have been trying many many things and run into issues.
It seems like I have a conflict with OT and Tahoma when connecting to my HD webcam.
I am using the Stopmotion function. 
On the first "call for connecting to the web cam it all seems fine. I used it close the "live view" and move to the drawing desk.
I then come back and wants to turn on the "live view again" and everything freezes up and crashes.

I am on Win7 pro. (Wich I love) and Am using logitech 9000 webcam.

Thanks in advance.
T.

_Originally posted by @Tragustauro in https://github.com/tahoma2d/tahoma2d/issues/868#issuecomment-1030891189_

**Comment by Tragustauro** [comment] 2022-02-12 17:06
Hello. Sorry about my ignorance. First time using Github.

I think I found out about the crash. For both OT and Tahoma.

webcam logitech 9000 
Newest driver updated. 
Webcam software works like a charm. Crisp picture .
Tahoma and OT installed.
Everything works like a charm.
On start up I disregard the startup menu where you can name your scene. I close it.
Activate "Stopmotion" control/function.
Webcam activated and no problem.
I test out my scene. (Paper-pencil linetest)
I do either of two things.

1: I save the scene
2: I close down with out saving.

On the next startup I have the option of starting all over again from fresh. Or I can choose 
"Recent Scene"
When I choose start all over agian in a new scene= Noproblem.
When I choose "RecentScene"  Tahoma starts to work on opening the "recent Scene" I chose. And Tahoma freezes/Crashes. For some reason I might get lucky that the scene actually starts up. But as soon as I touch "Stop-motion" it crashes.!???

So to work with out crashes I need not to save anything but start over.

Btw. Once the crash has been done I have no more connection to the webcam eventhoug I see it is still installed. Even in The webcams software I can not reach it!!..

I will try tonight to make a video of he problem

**Comment by Tragustauro** [comment] 2022-02-12 20:55
Hello. Sorry about my ignorance. First time using Github.

I think I found out about the crash. For both OT and Tahoma.

webcam logitech 9000
Newest driver updated.
Webcam software works like a charm. Crisp picture .
Tahoma and OT installed.
Everything works like a charm.
On start up I disregard the startup menu where you can name your scene. I close it.
Activate "Stopmotion" control/function.
Webcam activated and no problem.
I test out my scene. (Paper-pencil linetest)
I do either of two things.

1: I save the scene
2: I close down with out saving.

On the next startup I have the option of starting all over again from fresh. Or I can choose
"Recent Scene"
When I choose start all over agian in a new scene= Noproblem. (As I recall)
When I choose "RecentScene" Tahoma starts to work on opening the "recent Scene" I chose. And Tahoma freezes/Crashes. For some reason I might get lucky that the scene actually starts up. But as soon as I touch "Stop-motion" it crashes.!???

So to work with out crashes I need not to save anything but start over.

Btw. Once the crash has been done I have no more connection to the webcam even thoug I see it is still installed. Even in The webcams software I can not reach it!!..
Ohh by the way. I like to add.

I can only get in touch with the webcam by psychically removing the USB cord from the PC and plug it in again. (With out restart pc).

I will try tonight to make a video of he problem

**Comment by Tragustauro** [comment] 2022-02-12 20:57
I am not able to go to : 
C:\Users\yourusername\AppData\Local\Tahoma2D\Tahoma2D\cache\crashrpt\xxxx\crashdump.dmp
This path is not visible !?

**Comment by manongjohn** [comment] 2022-02-13 13:44
You may need to show Hidden folders.  The c:\Users\xxxx\AppData is usually hidden

**Comment by manongjohn** [comment] 2022-02-13 14:20
Although I cannot reproduce the crash you are having (I'm on Win10), i am noticing when I try to open a stopmotion scene I previously saved, it will attempt to connect to the camera, but doesn't really connect.  It will also immediately turn on `Live View`, though it won't actually use the camera until I click on the Live Frame in the timeline.

I wonder if this strange state is why you are crashing on startup.  I don't think it should be auto connecting to the camera when you first open the scene, much less put you in `Live View` mode right away, especially when you aren't really connected to the camera.

I don't see this odd state happening with the original T2D 1.2 release.  Something might have changed recently to cause this.

You appear to be using a more recent nightly.  Try using the original 1.2 release for now.  I will need to investigate this more.

**Comment by Tragustauro** [comment] 2022-02-13 14:27
Hello.

Thanks!!..

I am sitting now trying to get access to the crashdump.dmp file. It is quiet impossible at this moment. I will keep trying.

True what you say about the live feed.

It is just strange that it works the first time. And if I recall a saved scene it crashes and kicks off the cam. I physically have to  unplug and re plug the cam. And it kind of work again. It becomes very sketchy using

**Comment by Tragustauro** [comment] 2022-02-13 14:39
Btw.. Could it be because my computers earlier life was installed as a part of a server system?

**Comment by manongjohn** [comment] 2022-02-13 14:42
> Btw.. Could it be because my computers earlier life was installed as a part of a server system?

No. I doubt that.

**Comment by Tragustauro** [comment] 2022-02-14 01:27
Hello Sir.

I got pulled away from troubleshooting. I will jump at it tomorrow Asap.

Might there be a way for me to send you a screen Recording (video) of what is going on?

And thank you!!

T.

**Comment by Tragustauro** [comment] 2022-02-14 01:42
@manongjohn 
Was good once I started T up.

Close T.
Open T again.
Select last used (Lastopen) Scene.
Select live view.
T Crashes.

Tomorrow I put some more time into it.
its 02:42 Gotta slepp.


![CamTest001](https://user-images.githubusercontent.com/97757066/153786042-19b46080-7fa2-47c3-8bbe-6f5025817616.PNG)

**Comment by manongjohn** [comment] 2022-02-14 13:40
Was this a previously saved stop motion scene?  I don't see a stop motion level in the timeline which would normally trigger connection to the camera.  I see it's set for Level `A` - Frame 1 as if it were a brand new scene.

From the looks of your screenshot, it appears to have connected to your camera and is taking a live view?

If you can get to the crashdump file, that might give me a better idea of what is happening.

**Comment by artisteacher** [comment] 2022-02-14 13:53
If this is only an issue in previously existing scenes, is there anything from a stop motion capture that gets saved in the scene file?

**Comment by artisteacher** [comment] 2022-02-14 14:36
> Btw. Once the crash has been done I have no more connection to the webcam even thoug I see it is still installed. Even in The webcams software I can not reach it!!..

I wonder if the camera isn't disconnecting properly when T2D closes, so it's process doesn't end, which then prevents it from responding when restarting live view or trying to access it in the camera's app.

**Comment by Tragustauro** [comment] 2022-02-14 17:53
> If this is only an issue in previously existing scenes, is there anything from a stop motion capture that gets saved in the scene file?

Only on the first "startup" can I save the scene. And yes all the frames/Pictures gets saved in "sandbox".

The problem occurs when I either reopen this scene or just start a new scene to begin. At this point it seems like the Livewiev/camera gets thrown off or somehow gets stuck. And T and even logitechs software is not able to connect again.

It actually also says in logitech software that "No camera" detected.!?

While the logitechs software is open, I can literally unplug and re plug the cam on the back of the PC. And whoops it appears again. But T and OT can not connect. I then have to start a brand new scene and not reopen the last used scene.
I will try to see if I can reach the crash dump file.  For some reason I can not get to it just like that. Ill return

Thanks.

**Comment by Tragustauro** [comment] 2022-02-14 19:14
Ok here is a step by step visualization of the process including crash dump site.


![CamTest002](https://user-images.githubusercontent.com/97757066/153929845-c8ea4a54-d8ca-4244-89c3-7de10ff550ac.PNG)

![CamTest003](https://user-images.githubusercontent.com/97757066/153929863-6bdb001d-aaa7-47a2-827b-567c88797934.PNG)


![CamTest004](https://user-images.githubusercontent.com/97757066/153930059-377ae23e-61af-4758-8932-b867780ab221.PNG)


![CamTest005](https://user-images.githubusercontent.com/97757066/153930073-7631d5af-cd87-4c64-82db-b4e88a40aa72.PNG)


![CamTest006](https://user-images.githubusercontent.com/97757066/153930100-6773250f-e792-46b2-9881-6299a7725560.PNG)



![CamTest007](https://user-images.githubusercontent.com/97757066/153930117-134a3ad8-d632-4aa4-99f6-ebc3c4dc3058.PNG)


![CamTest008](https://user-images.githubusercontent.com/97757066/153930149-4bf9d107-d0c3-4682-9621-02aa69776481.PNG)

![CamTest009](https://user-images.githubusercontent.com/97757066/153930162-65ca1f96-1d4a-4d8c-9914-d37fa1d7a28d.PNG)


![CamTest010](https://user-images.githubusercontent.com/97757066/153930176-0beeec39-231b-4790-97b6-dd4b0d846767.PNG)


![CamTest011](https://user-images.githubusercontent.com/97757066/153930190-5d76cd1c-ee51-466b-8526-43c5b31ed115.PNG)


![CamTest012](https://user-images.githubusercontent.com/97757066/153930202-0ccb457e-5204-4107-ab54-208295da322c.PNG)


![CamTest013](https://user-images.githubusercontent.com/97757066/153930222-45c09cfc-676a-4683-9d31-63c228a9e362.PNG)


![CamTest014](https://user-images.githubusercontent.com/97757066/153930236-effec3dc-10f9-47ed-9816-41fe441850b0.PNG)


![CamTest015](https://user-images.githubusercontent.com/97757066/153930246-ecbd6fa5-a969-40fa-b786-fcd034deb32a.PNG)


![CamTest016](https://user-images.githubusercontent.com/97757066/153930266-eff40f05-215f-496d-b4e9-66a85c5b7ddc.PNG)


![CamTest017](https://user-images.githubusercontent.com/97757066/153930282-44420873-7c33-412a-8b8c-451dd26acf1f.PNG)


![CamTest018](https://user-images.githubusercontent.com/97757066/153930300-795c8900-e578-445e-abc5-133a3fc07475.PNG)

![CamTest019](https://user-images.githubusercontent.com/97757066/153930319-7a137ec3-41b9-4cdf-910b-8dd82cd5f8f5.PNG)


![CamTest020Crashdump](https://user-images.githubusercontent.com/97757066/153930337-76ea4b63-2125-4dd6-b5a5-cbb8c4ee8fe0.PNG)



![Capture](https://user-images.githubusercontent.com/97757066/153930357-97450145-e77b-40de-a4d1-8dde04440c0c.PNG)

In regards to crashdump site. It could be cool for Tahoma to have a place within to "Click" and it´ll take u directly to the "site". (Like opening the folder)

**Comment by Tragustauro** [comment] 2022-02-14 19:22
Here you can see I can´t even connect to the camera in it´s own software..

I have to unplug and replug the USB from the Pc and it pops right back up.

![CamTest021](https://user-images.githubusercontent.com/97757066/153931475-c3705559-3d7e-4ca0-b701-ea966a4b6e14.PNG)

![CamTest022](https://user-images.githubusercontent.com/97757066/153931495-dddb9b24-fd2b-419c-af02-eb2d64140d11.PNG)


![CamTest023](https://user-images.githubusercontent.com/97757066/153931530-804072a9-8beb-480d-9c73-864824b763c1.PNG)

**Comment by manongjohn** [comment] 2022-02-14 19:55
Does that little camera controller open when T2D connects to the camera or is it open before you connect? If open before you connect, please turn it off and see if it makes a difference?

Seems like whatever is causing the crash is happening outside of T2D since no crash files appear to be created.

If you start a new scene, take a few pictures then close T2D, is the camera still ok in it's own software? The crash is likely impacting how the camera is connected to your computer, since it isn't disconnecting normally. It may appear to be in use even though it is not which could explain why you need to reconnect the USB camera after a crash.

Have you tried this workaround to see if it helps: Open a blank scene, go to the Stop Motion room and select camera (turn on Live View if you want), then try loading the stop motion scene using File -> Open Recent Scene File -> yourstopmotionscene.

**Comment by artisteacher** [comment] 2022-02-15 14:35
So switching out of the camera (switching back to "Select camera" instead of "Hovercam Solo8") before saving and quitting prevents the issue on my end.

**Comment by artisteacher** [comment] 2022-02-15 14:58
In fact the scene itself doesn't matter. If I leave the camera active, save and then switch to a new scene, I just need to switch out of the camera before quiting T2D. Upon open, the camera works in existing scenes without issue.

**Comment by Tragustauro** [comment] 2022-02-15 18:59
@artisteacher 

Ohh interesting observation... and then again ...I just thought you also experienced pain.. Hahah..

I like to mention that I have three other line-test software installed. And Absolutely no problems within theses software.

When I saw OP and T2D I was gladly surprised. But It does not seem to work like at traditional 2Dlinetester or a stop motion package...the cool thing about T2D is the amount of functions in it.. A lot of good stuff in one package...

I have a Canon rebel camera and I might try to see if I can get that to work. I just need to find a "live-view" driver for that cam.
Thank you!!!!
........

**Comment by Tragustauro** [comment] 2022-02-15 20:31
I could also make another workaround. Just record the images from the webcam software. And Import the pictures into T2D xsheet and work from there...

**Comment by artisteacher** [comment] 2022-02-15 20:44
I've found that my Canon Rebel works great. 

> I could also make another workaround. Just record the images from the webcam software. And Import the pictures into T2D xsheet and work from there...


That's always an option. Though it would still be good to see if there's a way to get your webcam working properly. So switching out of the camera (back to select camera) before saving/closing has no impact for you? Or disconnecting the camera entirely before closing?
<img width="203" alt="Screen Shot 2022-02-15 at 3 39 48 PM" src="https://user-images.githubusercontent.com/21159116/154145495-ddf4cb34-9389-4247-a9be-15f113e43db3.png">

**Comment by Tragustauro** [comment] 2022-02-15 21:00
I would love for the webcam to work.
It would be so much easier to work with. It does not require much space and the picture is crisp and nice. And it is "only" for testing and timing out the animation. After that process I usually go to scanning...
You mean: "Stop live view" leavingT2D? 
.-.-.-.-.-.-.-.-.-.-.-
Ok.. the PC has been idle for most of the day. While writing this, I open the saved scene/project in T2D. It opens with camera selected. And T2D start to freeze. I cant scroll in the timeline or click anything. Everything has frozen.
So while this is going on (T2D is still open on the screen and freezing)  I physically unplug and re plug the webcam. Something "glitches" and now  I can use the live view again. Camera reconnected again. Something in T2D (and OPT) is causing the freeze of the cam. Is what I think since this is not happening in my other line test software installed.

I can now scroll the timeline. I scroll to the empty frame with the live view on and I see "my hand live" (or the next drawing) I want to "shoot".

**Comment by Tragustauro** [comment] 2022-02-15 21:03
@artisteacher 

Ohh by the way.

Using the Canon Rebel. Do by any chance have a tutorial on this?

Do I need a driver to connect to the Rebel? If so do you have a link to share?

**Comment by manongjohn** [comment] 2022-02-15 22:22
I've tried an Integrated Webcam and an external Logitech HD Pro Webcam C920 on a Win7 Pro and Win10 Pro laptop.  Unfortunately I am unable to duplicate this issue.  I have no problems opening a previously saved stop motion scene.

I have a question...normally when you reload a stop motion scene, it will automatically connect to the camera that was used, if it's still plugged in.  Usually there is some LED indicator on the camera showing it is connecting/disconnecting.  When I reload a scene, my indicator tends to flash 2x and then turns off instead of staying connected.  Does yours do that too?

I'm wondering when it's connecting/disconnecting like this it is somehow causing it to get stuck.

**Comment by Tragustauro** [comment] 2022-02-15 22:26
Ohh I did not check that light. The cam is face down and I never looked at that. I will try to see..

**Comment by Tragustauro** [comment] 2022-02-15 22:31
Interesting observation.
I just checked.


Opening a"saved scene/Project"  The cam is flashing twice. And the whole thing freezes.
![9000](https://user-images.githubusercontent.com/97757066/154160667-afb8103b-fbb4-4c82-bed9-f0053ba56faf.jpg)

**Comment by manongjohn** [comment] 2022-02-15 22:43
I wonder if the rapid connection/disconnection might be somehow glitching out the camera connection.  T2D may be having issues with your camera's driver when it does that causing it to get stuck/crash.

I'll see if I can stop it from doing that.  Ideally I wouldn't want it connecting to the camera at startup like that.

**Comment by Tragustauro** [comment] 2022-02-15 22:50
Right!?... 

This does not occur in the other line test software that I use. It is really wierd. And what I think is "crazy". I can unplug and re-plug the cam and it´s back again.!??

**Comment by Tragustauro** [comment] 2022-02-15 22:52
@manongjohn 

You mentioned: "Seems like whatever is causing the crash is happening outside of T2D since no crash files appear to be created".

Is there a way to check this?

**Comment by artisteacher** [comment] 2022-02-16 00:10
> You mean: "Stop live view" leavingT2D?

No - I mean deselecting the camera before closing:
![deselect-cam](https://user-images.githubusercontent.com/21159116/154169095-2d956ac9-ea87-4dbd-9194-5fe91fe59dc1.gif)
So that "Camera" is left on "- Select Camera -".

> Do I need a driver to connect to the Rebel? If so do you have a link to share?

If your firmware is outdated, it's always a good practice to update it. Just [find your camera model here](https://www.usa.canon.com/internet/portal/us/home/support). On its support page, there are links to download firmware updates and the EOS Utility if you end up needing it.

I don't have a tutorial atm. Start by opening T2D. Connect the Canon to the computer using the appropriate cord. Turn the camera on. Select the camera in the Stop Motion room.

> Is there a way to check this?

Crash reports should be available in Event Viewer in Windows or Console on macOS

**Comment by Tragustauro** [comment] 2022-02-16 01:11
Ok cool.

I thank you for your time.

**Comment by artisteacher** [comment] 2022-02-22 20:41
@manongjohn - I think this can be closed.

**Comment by manongjohn** [comment] 2022-02-22 20:45
Thanks for following up. I didn't properly note it in the PR so it didn't auto close it once it merged.

**Closed by manongjohn** 2022-02-22 20:45 UTC
