### ISSUE TITLE
Can't start the NIGHTLY (but no problem with the OFFICIAL)

### ISSUE THREAD

**Issue by ArchieLinux** [tahoma2d/tahoma2d#1431] opened 2024-03-24 21:17 UTC
### Bug Description

On my Linux (Arch/EndeavorOS/i3wm) set ups (on multiple platform hardware), I have no problem running the Tahoma2D AppImage labeled as "Official Release" [v1.4.1 - 2024-02-01T00:07:47Z].

But I've tried repeatedly following the same download/extract steps on the Nightlys (different "nights") and keep getting this nealry instant error message:

![Screenshot-Tahoma-1 4-Load](https://github.com/tahoma2d/tahoma2d/assets/119451251/70d7e6bc-1557-449d-bfc7-e2b5f72550de)
(say: `Critical 1.4.1. Undefined or empty ""`)

I'd share more info but the program never opens beyond this so I have no trace or debug data to share.

This error is appearing on Dell, MacBookPro 2011, iMac 2019, all of which are running Arch Linux configurations. 

Since I'm following the same steps for both the Official Release and the Nightly(s)-  and the former works and latter does not - I'm assuming there's either something about the nightly files or there's some configuration step I'm missing.

I imagine this is an easy fix for someone "in the know"... Any suggestions welcomed!

### Steps to reproduce

Download Nightly Tahoma2D
Extract to a folder (tried various locaitons)
Attempt to open AppImage Tahoma2D file
See error message almost instantly.

### Relevant logs/screenshots

![Screenshot-Tahoma-1 4-Load](https://github.com/tahoma2d/tahoma2d/assets/119451251/29fc4e87-7919-49a6-8b55-19c0da5fe0f9)

### Software Version

1.4.1

### Software Version Information

Current (today) + previous nightlys

### Operating System

EandeavorOS / Arch Linux (i3 tiling manager)

### Graphics Card

Various - all produce same outcome

### Drawing Tablet

XP-Pen Deco and ArtistPro (and/or unplugged)

**Comment by manongjohn** [comment] 2024-03-24 21:29
Strange.  There is technically no difference between the Official release and the Nightly.  Both are compiled and packaged exactly the same.

What was the last night nightly you tried?

**Comment by ArchieLinux** [comment] 2024-03-24 23:13
I  tried again this afternoon before posting the issue, so it's the currently posted "Nightly" as of now. 

FWIW, I get the same result on three different hardware setups (same Arch/EndeavorOS/i3 confi) ... with the only difference being that the error dialog shown appears on the Apple hardware 2011 MacBookPro and 2019 iMac desktop (not using Mac OS, but Linux) and on the Dell Optiplex I get no error but the screen just locks up and hangs on the first message box stating "Initializing Tahoma2D" - with no further progress, eventually halts and exits. 

Strange indeed! If I weren't able to successful install/run the "Official" release, it might be less strange ;-)

**Comment by ArchieLinux** [comment] 2024-03-24 23:44
Okay, I think I may have figured it out ...

When I extract and run the NIGHTLY, there's a "profiles" folder that appears alongside the Tahoma2D, but the profiles folder buried deep within the Tahoma2D director under "users" in empty. 

However, when I cut/paste the (properly located) "profiles" directory created in the OFFICIAL release that includes relevant files (naming me as a user) into the otherwise empty "profiles" directory of the NIGHTLY tree structure, then the NIGHTLY opens properly.

My suspicion is that for some reason the NIGHTLY extract is not creating the same profile info as the OFFICIAL extract.

Could this help aim efforts in the right direction?

**Comment by ArchieLinux** [comment] 2024-03-25 00:03
UPDATE: Just confirmed again: when I copy that stray "profile/users" folder (that is appearing on the same top level in my directory tree as the top level folder that contains everything for Tahoma2D) and paste it deep into Tahoma2D tree (Tahoma2D/tahomastuff/profiles/users) then I can get the NIGHTLY to run without errors. 

Once this is done, and I delete that even delete that top level profiles folder, Tahoma2D then seem to run fine.

Hopefully this is useful info.

**Comment by manongjohn** [comment] 2024-03-25 00:08
> I get no error dialog but the screen just locks up and hangs on the very first loading message box stating "Initializing Tahoma2D" - with no further progress, eventually halts and exits.

There was a bug with recent Linux builds but I merged that this morning so it should have been fixed with the latest.  I confirmed it was fixed in my Ubuntu Linux environment. 

Are you sure you have the latest nightly?

Also, there is GCC and a CLANG version of the Linux builds.  Which one are you using? Both work for me without issues, but the official one is the GCC version.  Did you try both?

Regarding the /home/xxxx/profle folder, try deleting it.   Also if you have a `/home/xxxx/.config/Tahoma2D` folder created, delete that too.  Then try a newly extracted T2D and see if it creates it again.

If these were created in error, it might be trying to use that before what's in the tahomastuff folder.

**Comment by ArchieLinux** [comment] 2024-03-25 00:17
Couple of replies ...

Definitely using the current (i.e., as of minutes ago) "Nightly" build and tried again with fresh download minutes before posting above.

Been using the GCC version only, not CLANG. Would be happy to try CLANG but it sounds like the GCC is already preferred.

As for those (Tahoma2D-related) profile folders, turns out I am now spotting them in various places, everywhere that I've extracted Tahoma2D while trying to resolve the error load message ... i.e., Linux Home, Desktop, Downloads, various others, and there are a rash of profile/user folders created at the top levels of each. 

I will delete them all and forge ahead. Will report back if I glean anything further.  :-)

[BTW, I trust it goes without saying that the Tahoma2D project is F-A-N-T-A-S-T-I-C... and your efforts and support in pulling us all forward into the future is awesome.]

**Comment by ArchieLinux** [comment] 2024-03-25 01:07
UPDATE: Something odd continues ... I have installed and reinstalled multiple times and after successfully getting things to run by deleting the profiles folders that get created at the top level of installation (and sometimes having to use  them to overwrite the user folder content within Tahoma2D file structure), after successfully using the program, subsequent attempts to open it again prompt that same critical error described above.

I cannot seem to find a reason why sometimes this error is thrown - which I seem to be able to overcome by either deleting /copying the profile/user contents at the top level to properly located within the Tahoma2D tree structure again - and sometimes not. 

If I figure it out, I'll be sure to provide another update. But so far, the error seems to reoccur intermittently.

**Comment by manongjohn** [comment] 2024-03-25 01:27
Something is causing the program to misread the root folder, which is why it keeps making the profiles directory outside the tahomastuff folder.  Not sure why it isn't happening for me but happens for you.

Can you send me the output when running the Tahoma2D.AppImage from command line? I don't expect it to tell me anything but maybe I can glean something from it.

**Comment by manongjohn** [comment] 2024-03-25 01:43
Out of curiosity, how are you executing the Tahoma2D.AppImage?  Are you inside the Tahoma2D folder when running the appimage?

**Comment by ArchieLinux** [comment] 2024-03-25 01:55
> Something is causing the program to misread the root folder, which is why it keeps making the profiles directory outside the tahomastuff folder. Not sure why it isn't happening for me but happens for you.
> 
> Can you send me the output when running the Tahoma2D.AppImage from command line? I don't expect it to tell me anything but maybe I can glean something from it.
![Screenshot_20240324_195141](https://github.com/tahoma2d/tahoma2d/assets/119451251/5e574f6d-b82c-4b30-9af8-9f090911c0bd)

Hopefully this is readable. Until now I've been using a GUI file manager (double click) to open Tahoma2D rather than a CLI approach - which provides no additional info beyond the error dialog. 

But here's a straight screen capture of the process before the error dialog appears... Hope this helps!

**Comment by manongjohn** [comment] 2024-03-25 02:03
Can you redo the CLI command, but ensure you are inside the Tahoma2D folder when you execute it? Running CLI from anywhere outside of the T2D folder will result in what you are getting.

The only thing I can suggest, if you have time and patience, is go backwards through the nightly archives and find out where this problems started.  Then I can at least look at what was in that change that might be causing this.

Btw, thank you for the positive feedback.  It's always welcome and very much appreciated. :)

**Comment by ArchieLinux** [comment] 2024-03-25 02:19
You've been very generous with your time and talents ... I will focus attention on this going forward to see if I can provide meaningful insight. For the time being, I seem to be able to successfully load the Nightly by changing the terminal directory to where the AppImage is stored and running the Tahoma2D.AppImage file through CLI without further incident. 

Perhaps my GUI file manager (lately: nemo) has been interfering in some way. Frankly, this is the ONLY application I use that is an AppImage - I've avoided them like the plague ... but Tahoma2D is SO GOOD it makes me get over my hesitations. Hence it's likely I'm simply not used to invoking apps this way and have cluttered up the tasks required.

Meanwhile, thank you again for your helpful suggestions. Hopefully this exchange is also of value to other newcomers in the future.

**Comment by manongjohn** [comment] 2024-03-25 02:34
Interesting.  I use the stock file manager in Ubuntu and haven't had any problems when double-clicking the AppImage.  Why double-clicking through your file manager seems to be having problems is definitely perplexing since you are in the folder already.

Hopefully other Linux users who might be watching can provide some feedback whether they can get the recent nightlies working or not.

**Comment by ArchieLinux** [comment] 2024-03-25 03:17
You comments above got me thinking and testing further and I think as a result you've prompted me to stumble upon something that may be at play here...

Within the GUI file manager ("nemo"), if I open subfolders from Home (Desktop/Tahoma2D) and click on the AppImage file, I get the errors described above. If I first navigate within the file manager GUI to the actual Tahoma2D folder, it opens without error. 

I tested the same from the CLI of the terminal emulator and lo' and behold: same results.

In other words, whether using a GUI file manager or directly calling the AppImage from the CLI, it's important to already be residing in the folder in which the AppImage (and related Tahoma2D resources) resides. 

Your comment above about a repeat from a different folder starting point let me down this path. 

I haven't tested this out exhaustively, so perhaps there are other factors at play, but for the benefit of anyone who follows this thread trying to overcome the loading error seen above, it may be as simple as navigating to the specific folder in which the AppImage file resides and invoking it (regardless of terminal or GUI file manager) from there.

If so, hopefully this helps others coming along in the future.

**Comment by manongjohn** [comment] 2024-03-25 13:55
Ah.  So running the portable T2D in Linux (even Windows) requires that your Current Working Directory is the Tahoma2D folder.  Even those who attempt to manually create shortcuts in Linux need to set up the command to first change to that directory before starting up the AppImage. (typically something like `cd /...../Tahoma2D && Tahoma2D.AppImage`)

Sounds like the "panel" method you were using to run the application does not set the current working directory where it is running from, hence the issue you are encountering.

**Comment by ArchieLinux** [comment] 2024-03-25 19:54
Yes, indeed. I caught the instructions about keeping certain key files in the same directory but must have missed the part about having to navigate to that directory to launch. My oversight ... sorry for such a simple issue taking up your valuable time. 

Which is a good time to mention that I tried to make a financial contribution but apparently PayPal is no longer an option on github. No other options seem to be provided. Alternatives?

**Comment by ArchieLinux** [comment] 2024-03-25 20:05
> I only take donations (one time or reoccuring) through the Github Sponsorship program. I'm not sure how people do that without PayPal. I never expect it but it is a wonderful surprise to see an email when someone does. 😁

Well, if you come up with another avenue, let us know! Apparently Github has disconnected itself from PayPal for some reason and no other option appears on the screen when trying. :man_shrugging: Thanks so much for your tireless work on Tahoma2D. You deserve our support.

**Closed** 2024-03-26 00:24 UTC
Labels: bug

**Comment by ArchieLinux** [comment] 2024-03-26 00:25
Thanks again to @manongjohn for walking me through my AppImage opening glitches. 
Not the app's fault ... apparently just my own launching issues.

**Comment by manongjohn** [comment] 2024-03-26 00:29
All good. I was more worried I broke something...which has happened in the past. 😄

Luckily someone found the 1 issue with the stuck Initialization recently so I was able to fix it quickly.

Happy Animating!
