### ISSUE TITLE
Set key problem in Plastic Tool

### ISSUE THREAD

**Issue by HeliumVola** [tahoma2d/tahoma2d#527] opened 2020-11-22 13:01 UTC
Create a mesh, create a skeleton, switch to animate, now press SET KEY from the workspace navigation bar, now move to frame 12, move a vertex of the skeleton (this will create a new key). Now play and it won't animate.

but

Create a mesh, create a skeleton, switch to animate, now move a vertex of the skeleton (creates a key frame) , now move to frame 12, move a vertex of the sekeleton (this will create a new key). Press play and it animates.

So the SET KEY from the navigation bar seems not to work.

**Comment by artisteacher** [comment] 2020-11-22 15:03
You mean the set key button in the Viewer? I think that command works with the animate tool, not the plastic tool. Based on the manual, I think this is a deliberate design choice and not a bug. 

I'd love for the keyframe button to add keys based on the active tool though. I think it's expected, especially since setting keyframes by moving the skeleton changes the display of the set key button.

You can set an initial key without moving the skeleton by right-clicking in the viewer and setting a key from the context menu.

**Comment by HeliumVola** [comment] 2020-11-22 15:11
>You mean the set key button in the Viewer? I think that command works with the animate tool, 

yes

>not the plastic tool. Based on the manual, I think this is a deliberate design choice and not a >bug.

ok

>I'd love for the keyframe button to add keys based on the active tool though. I think it's >expected, especially since setting keyframes by moving the skeleton changes the display of the >set key button.

Exactly. It took me half an hour the understand what I am doing wrong or why it is not animating :D

>You can set an initial key without moving the skeleton by right-clicking in the viewer and setting >a key from the context menu.

thanks.

**Comment by manongjohn** [comment] 2021-01-27 14:50
Closing as it doesn't appear to be a bug (correct me if I am wrong).  I do however see a potential enchancement request mentioned in the discussion which should be opened under an Enhancement request

**Closed by manongjohn** 2021-01-27 14:50 UTC
Labels: bug
