### ISSUE TITLE
Timeline Icons not showing

### ISSUE THREAD

**Issue by BertWik** [tahoma2d/tahoma2d#1193] opened 2023-07-25 07:57 UTC
### Bug Description

In the latest Nightly build the icons on the timeline command bar are not shown on the tablet display. (They are shown on the laptop display)

### Relevant logs/screenshots

![Scherm­afbeelding 2023-07-25 om 09 54 04](https://github.com/tahoma2d/tahoma2d/assets/140490349/1eb7ea33-2ceb-48a0-8197-e746a25ccc18)

### Software Version

1.3.1

### Software Version Information

2023-07-25T03:05:06Z

### Operating System

MacOS Ventura (13.4.1)

### Drawing Tablet

Huion Kamvas 24 plus

**Comment by manongjohn** [comment] 2023-07-25 14:16
Looking into as I found another issue with missing icons that is likely related.

For now, try enabling the following to see if it shows up:

1. Enable `Preferences` -> `General` -> `Show Advanced Preferences and Options`
2. Restart
3. Enable `Preferences` -> `Interface` -> `Show Icons In Menu`
4. Restart

**Comment by BertWik** [comment] 2023-07-25 14:24
Thank you for the quick reaction.

It works.

**Comment by manongjohn** [comment] 2023-07-25 20:53
I cannot seem to reproduce this issue in 10.15 (Catalina) environment using a local build.   I wonder if anyone on any later macOS versions is having similar issues with the nightly.

@BertWik I pushed a fix under PR #1195 which I wonder if it will fix the issue you are experiencing.  When the macOS build artifact is ready on that PR, can you check it out to see if the problem still exists?

**Comment by artisteacher** [comment] 2023-07-31 21:38
Not a problem for me on Ventura with the latest nightly.

**Comment by BertWik** [comment] 2023-08-01 13:12
The same  issue occurs in the latest nightly build (2023 - 07 - 30).
The icons do dhow up on the laptop screen but not on the tablet screen.

**Comment by artisteacher** [comment] 2023-08-02 00:30
Does having the tablet screen mirrored or used as an extended desktop make any difference? Does having T2D open or closed before connecting the tablet make a difference? Are the tablet drivers up-to-date? Does the quick toolbar have the same problem?

**Comment by manongjohn** [comment] 2023-08-02 03:04
> The icons do dhow up on the laptop screen but not on the tablet screen.

I can duplicate this on my windows laptop and external tablet.  It appears to be due to the device resolution being different between my laptop (4k) and tablet (HD). When they are the same it shows fine in both. When they arent it doesn't.

Will work on fixing it.

**Closed** 2023-08-11 02:52 UTC
Labels: bug

**Comment by BertWik** [comment] 2023-08-13 09:24
The latest nightly build (08-11) does not open on a MacBook (It crashes immediately)

**Comment by manongjohn** [comment] 2023-08-13 12:40
Currently trying to fix. Hope to have it fixed soon.

**Comment by manongjohn** [comment] 2023-08-16 00:23
@BertWik The macOS nghtly should be fixed now.

**Comment by BertWik** [comment] 2023-08-19 08:58
The new nightly build (August 15) crashes when trying to import preferences.
