### ISSUE TITLE
Plugin SDK samples does nothing.

### ISSUE THREAD

**Issue by fomEbiTal** [tahoma2d/tahoma2d#1588] opened 2024-09-29 13:08 UTC
### Bug Description

I compiled the example plugin samples (From the plugins repo that you have on your account) from $ROOT_DIR/opentoonz_plugin_utility/plugin_sdk/samples and they do nothing. Just shows a black square with a circle in it. I want to try to understand how the plugin works, but I have no idea if this is a Tahoma2D bug or if the plugins are incomplete.

### Steps to reproduce

Compile the plugin samples, move the .plugins to the correct directory, and activate the vfx plugins. Nothing interesting happens.

### Relevant logs/screenshots

![Multiplugin](https://github.com/user-attachments/assets/2158e68d-5dbd-4afc-b629-fd1b9b374848)

### Software Version

1.4.4

### Operating System

Windows 11 and GNU/Linux

**Comment by manongjohn** [comment] 2024-09-29 13:42
Regarding the plugin you compiled and show in the image: this particular type of plugin is called a Zerary-Fx, which means that it doesn't take any input but instead generates an image based on whatever parameters are provided and what they do to create an image.  Examples of this type of Fx, Checkboard, Gradients.  Depending on what Fx you are interested in making, this is probably not what you want to start with.

If you are looking for an Fx where it takes an image as input and applies an Fx to it, I suggest looking at the actual plugins in the `Dwango` or `Wolf` directories.

Closing this as it's not a bug.  Feel free to join T2D's Discord if you would like to discuss plugins, development or otherwise.

**Closed by manongjohn** 2024-09-29 13:42 UTC
Labels: bug

**Comment by fomEbiTal** [comment] 2024-09-29 15:25
> Regarding the plugin you compiled and show in the image: this particular type of plugin is called a Zerary-Fx, which means that it doesn't take any input but instead generates an image based on whatever parameters are provided and what they do to create an image. Examples of this type of Fx, Checkboard, Gradients. Depending on what Fx you are interested in making, this is probably not what you want to start with.
> 
> If you are looking for an Fx where it takes an image as input and applies an Fx to it, I suggest looking at the actual plugins in the `Dwango` or `Wolf` directories.
> 
> Closing this as it's not a bug. Feel free to join T2D's Discord if you would like to discuss plugins, development or otherwise.

Though my only complain is that none of the Wolf or Dwango plugins show an example of manipulating a camera like set of coordinates such as similar to the free distort or the perspective distort plugins. I don't know if the SDK has such means of implementing something similar to it.

**Comment by fomEbiTal** [comment] 2024-09-29 16:02
@manongjohn 
What exactly is a 'Zerary-Fx' because information on it is almost nonexistent.

**Comment by manongjohn** [comment] 2024-09-29 16:10
> What exactly is a 'Zerary-Fx' because information on it is almost nonexistent

Most Fx do not have an associated column for it. Zerary-Fx, when created have a column on the timeline/xsheet created for it.  Essentially, they are treated like a regular level but the fx, itself, generates the image from nothing. As such, these fx have 0 import ports.

Not sure where the term "zerary" comes from and usually isnt mentioned in any general user documentation. It is a special fx distinction in code.

**Comment by fomEbiTal** [comment] 2024-09-29 16:13
> > What exactly is a 'Zerary-Fx' because information on it is almost nonexistent
> 
> Most Fx do not have an associated column for it. Zerary-Fx, when created have a column on the timeline/xsheet created for it. Essentially, they are treated like a regular level but the fx, itself, generates the image from nothing. As such, these fx have 0 import ports.
> 
> Not sure where the term "zerary" comes from and usually isnt mentioned in any general user documentation. It is a special fx distinction in code.

Do you know all the types of fx there is? There is zerary, but what else? I've found in a header file include/fxtypes.h it listed two enums and about 6-7 elements per enum.

**Comment by manongjohn** [comment] 2024-09-29 16:21
There are really only  2 fx...regular fx (no column) and zerary fx (column created) .   Any other fx types you see in that header file are highly specific nodes that are not a base for new fx.

**Comment by fomEbiTal** [comment] 2024-09-29 16:24
> There are really only 2 fx...regular fx (no column) and zerary fx (column created) . Any other fx types you see in that header file are highly specific nodes that are not a base for new fx.

I guess my final question is: even though I can't really think of anything at this very moment what to make with it, is it possible to make an FX that has its own camera of sorts to it like the free distort or perspective distort. I'm just wanting to clear up some confusion. Though I do wish to also know: why do you not recommend following the way the multiplugin and the two others in the samples directory are made? Is it because they're zerary plugins or something else?

**Comment by manongjohn** [comment] 2024-09-29 17:07
I've not done any real Fx development nor have I done any plugins therefore I cannot speak to what can be done within an external plugin.  Not sure if it's possible to create on-screen controls like the free/perspective distort have with an external plugin.  That might be a reason why those particular fx are integrated primarily within T2D and not handled as external plugins.  Not sure If there is even an example of an external plugin that creates on-screen controls.

As far as not recommending those particular samples...I've never really looked at those plugins so I don't know if they show anything worthwhile beyond the bare basics.  I  suggested the other ones since they are used actively by some and potentially showcase more advanced examples of plugins that could provide you more insight when building one.
