### ISSUE TITLE
Program crash!!

### ISSUE THREAD

**Issue by animator1029** [tahoma2d/tahoma2d#660] opened 2021-04-10 13:20 UTC
I downloaded Tahoma2d and it turned out to be a portable ZIP file. So I expanded the file and opened the app. But every time I click on the Tahoma2d app in the ZIP file, it crashes. I have tried to restart my laptop but it isn't working at all. Please help me with this issue. 

**Device Information:**
I have a Windows 10 Laptop

**Comment by manongjohn** [comment] 2021-04-10 13:26
After download, extract the contents of the .zip file.  Do not attempt to run while still in the zip. It should create a Tahoma2D folder after extracting. 

Keep every thing in the folder. Move the entire folder somewhere else. For now, I recommend moving to Desktop or even to Program Files.

Double-click the Tahoma2D.exe to run.

**Comment by animator1029** [comment] 2021-04-10 13:33
> After download, extract the contents of the .zip file. Do not attempt to run while still in the zip. It should create a Tahoma2D folder after extracting.
> 
> Keep every thing in the folder. Move the entire folder somewhere else. For now, I recommend moving to Desktop or even to Program Files.
> 
> Double-click the Tahoma2D.exe to run.


But could you just to be sure send a video or something? I am not so common with portable ZIP files and my English isn't that good😅.

**Comment by animator1029** [comment] 2021-04-10 13:36
![image](https://user-images.githubusercontent.com/73611121/114271588-6afd3500-9a12-11eb-995d-325417dfd1aa.png)

I get this after clicking on the app, and then it crashes.

**Comment by animator1029** [comment] 2021-04-10 13:36
> ![image](https://user-images.githubusercontent.com/73611121/114271588-6afd3500-9a12-11eb-995d-325417dfd1aa.png)
> 
> I get this after clicking on the app, and then it crashes.

I can't click or do anything at all.

**Comment by animator1029** [comment] 2021-04-10 13:57
> After download, extract the contents of the .zip file. Do not attempt to run while still in the zip. It should create a Tahoma2D folder after extracting.
> 
> Keep every thing in the folder. Move the entire folder somewhere else. For now, I recommend moving to Desktop or even to Program Files.
> 
> Double-click the Tahoma2D.exe to run.

It doesn't work, It keeps crashing...........................

**Comment by manongjohn** [comment] 2021-04-10 14:05
How far are you getting before it crashes? Are you getting any error messages?

After it crashes, open Windows Event Viewer. Click on Windows Log -> Application. Look for an Error log and let us know what it says. It might explain why it is crashing.

**Comment by animator1029** [comment] 2021-04-10 15:13
There are no error messages at all.

It says that it is an application error.

**Comment by artisteacher** [comment] 2021-04-11 22:50
It might be worth trying the alpha release. If there's still a crash, I believe it will generate its own crash report.

**Comment by manongjohn** [comment] 2021-04-11 22:57
I recently had an issue where I downloaded and tried to run Tahoma2d and it would start but eventually crash with only an error in Windows Event Viewer, failing on ucrtbase.dll. i turned off anti-virus to run it the 1st time and it started. After that i reenabled anti virus and it was fine.

So, try turning off anti-virus and see if that works. Otherwise, you need to let us know what it says in Windows Event Viewer to see what it might be.

**Comment by animator1029** [comment] 2021-04-12 08:48
![image](https://user-images.githubusercontent.com/73611121/114367260-900db700-9b7c-11eb-9a53-cd2dd6dd33cf.png)
 Now when I open it, it says this.

**Comment by animator1029** [comment] 2021-04-12 08:51
> It might be worth trying the 1.2 alpha release. If there's still a crash, I believe it will generate its own crash report.

How do I download that? I can't find it on the site.

**Comment by animator1029** [comment] 2021-04-12 09:05
> It might be worth trying the 1.2 alpha release. If there's still a crash, I believe it will generate its own crash report.

This one crashes too.
I have seen a lot of videos and I think that Tahoma2d is a very  good program.  so that's why I am sticking to shit

**Comment by manongjohn** [comment] 2021-04-12 10:57
If you have special characters in your username, it's possible it is having a hard time finding stuff it needs when it runs.

Try moving the entire Tahoma2D folder to `C:\Program Files` or just `C:\` to make sure.

**Comment by animator1029** [comment] 2021-04-12 14:42
I think that my laptop isn't good enough for this program. Do you guys now any other animation programs that also have a portable ZIP file version? Because it takes not that much room.

**Comment by animator1029** [comment] 2021-04-13 06:37
> If you haven't tried it yet, try putting the entire Tahoma2D folder as C:\Tahoma2D.

How do I do that? I haven't learned these things yet😅

**Comment by animator1029** [comment] 2021-04-13 06:50
https://user-images.githubusercontent.com/73611121/114508935-3c12d900-9c35-11eb-83f4-ab7af0eddc73.mp4


https://user-images.githubusercontent.com/73611121/114508942-3ddc9c80-9c35-11eb-85b9-da7020a03f97.mp4

This is what happens....................................

**Comment by manongjohn** [comment] 2021-04-13 10:37
Right-click the Tahoma_windows.zip and

**Comment by manongjohn** [comment] 2021-04-13 10:41
Looks like you didn't unpack the download and still trying to run it inside the .zip file.

Right-click Tahoma2D_win.zip and look for a way to Extract or Uncompress or Unzip the contents. After you extract, there will be a Tahoma2D folder which you can move to any place on your machine.

**Comment by animator1029** [comment] 2021-04-13 10:50
![image](https://user-images.githubusercontent.com/73611121/114541321-d9323980-9c56-11eb-8ab4-960ed36bd30d.png)

I did extract it.........................

**Comment by manongjohn** [comment] 2021-04-13 11:14
What are the specs of your computer and what video card do you have? Are you running any anti-virus software?

Please open Event Viewer and go to Windows Log -> Application Logs and look for an error log explaining the crash.

Unfortunately without answering some of these questions it will be difficult to find out what the problem is.

**Closed** 2021-04-13 11:20 UTC
Labels: bug

**Comment by artisteacher** [comment] 2021-04-13 14:59
I'm not seeing the tahomastuff folder in those videos. Is it in the Tahoma2D-win or Tahoma2D_Windows directories?

**Comment by artisteacher** [comment] 2021-04-13 23:59
@animator1029 - Do you happen to be using a tablet or dual monitor system of some kind?
