### ISSUE TITLE
Dragging selection handles on xsheet does not move audio levels.

### ISSUE THREAD

**Issue by melieconiek** [tahoma2d/tahoma2d#819] opened 2021-10-16 12:03 UTC
**Describe the bug**
Dragging selection handles on xsheet does not move audio levels.

![a](https://user-images.githubusercontent.com/42298081/137586554-fe738735-bc00-4a6c-bad6-9085437132ef.gif)

**Device Information:**
 - OS: Windows
 - Tahoma2D Version: 8/27/2021

**Comment by artisteacher** [comment] 2022-01-18 02:37
I see this too, using macOS and the latest nightly build. Every other level type I've tested moved forward in response to the selection.

**Comment by manongjohn** [comment] 2022-04-11 12:49
Technically this is not a bug.  It was specifically coded to ignore sound columns.  As such, I'm removing the bug label.

Having said that, I already have a fix for this which I'll consider a minor enhancement and can include in 1.3.

Question:  Should sound be refreshed after dragging is complete/release the mouse button?  I know there is some concern with refreshing sound when there are a lot used in the scene.

**Closed** 2022-04-16 13:46 UTC
