### ISSUE TITLE
Cannot drag/drop columns in timeline

### ISSUE THREAD

**Issue by HeliumVola** [tahoma2d/tahoma2d#522] opened 2020-11-21 18:37 UTC
Cannot drag/drop columns in timeline. IN X-Sheet it is working, but not in the timeline.

**Comment by DarrenTAnims** [comment] 2020-11-22 11:31
I can drag/drop columns in the timeline. Can you share a video (using either ScreenToGif, OBS or other screen recording software) showing what you're doing. But if you grab the coloured bar in the column header, you can reorder the columns.

**Comment by artisteacher** [comment] 2020-11-22 15:08
It works for me if I drag the thin dragbar in the layer header. You do need to be careful of where you drag from. If you are slightly off target, you might start a selection instead of drag/drop.

**Comment by HeliumVola** [comment] 2020-11-22 15:15
Yes. After 10min I got it. But not the best usabilty and I do not understand, why not the whole area can be used as a drag/drop starting point.

**Comment by HeliumVola** [comment] 2020-11-22 15:20
Ah now I see. I can click, hold and drag the mouse to multiselect colmuns. Thats why drag/drop cannot be started in this area. But not sure if this handling is good by design. Why not a standard multiselect with SHIFT, CTRL?

**Comment by artisteacher** [comment] 2020-11-22 15:30
It probably makes for easier selections with a stylus.

**Comment by HeliumVola** [comment] 2020-11-22 15:39
Maybe, but drag/drop with a stylus will be much more hell with this design :D. Why not using the thumb as drag/drop area or adding an extra move icon between thumb and name. At least something that is bigger and easier to understand.

**Comment by manongjohn** [comment] 2021-01-27 13:53
Closing as it's not a bug.  Feel free to open a separate enhancement request for improvements to column selection where the best method can be discuss further

**Closed by manongjohn** 2021-01-27 13:53 UTC
Labels: bug
