### ISSUE TITLE
Drawing delay on vector and smart raster levels

### ISSUE THREAD

**Issue by pikhosh** [tahoma2d/tahoma2d#1007] opened 2022-06-03 08:43 UTC
### Bug Description

- No problem with drawing with the mouse.
- No problem with drawing with the pen on the raster levels.
- No problem in v1.2.

### Steps to reproduce

1. Open Tahoma2D.
2. Select the brush tool.
3. Create a vector or smart raster level.
4. Start drawing.

### Relevant logs/screenshots

https://user-images.githubusercontent.com/73311467/171819316-597077e5-7350-487b-baa1-a9a9c94e32c4.mp4

### Software Version

1.3

### Operating System

Fedora 36 and KDE neon

### Graphics Card

AMD RX 570

### Drawing Tablet

XP-PEN G640

**Comment by beeheemooth** [comment] 2022-06-03 09:01
Hmm, I remember version 1.3 when attempts were made to move to OpenGL. As a result, this significantly affected the performance of the brush, which was noted by many users. After this version, a lot of work has been done to improve the performance of the Brush Tool. You need a newer version of the program (but don't know how it is with Fedora OS)

**Comment by manongjohn** [comment] 2022-06-03 11:25
It was OT 1.2 that had that problem.  We had to release 1.2.1 because of the issues trying to move to OpenGL.

@pikhosh The official linux downloaded is the "clang" version.  I'm curious if the "gcc" version would have the same problems. Try downloading the gcc version from the github release page and see if also has that problem.

**Comment by pikhosh** [comment] 2022-06-03 22:09
> It was OT 1.2 that had that problem. We had to release 1.2.1 because of the issues trying to move to OpenGL.
> 
> @pikhosh The official linux downloaded is the "clang" version. I'm curious if the "gcc" version would have the same problems. Try downloading the gcc version from the github release page and see if also has that problem.

No difference.

**Comment by 2blackbar** [comment] 2022-06-26 20:37
I think drawing in tahoma /opentoonz needs serious rewrite, its quite laggy compared to other drawing software like gimp, i think it was not written to draw but to colorise scanned drawings in it so the drawing engine is quite crude and very basic, its most important feature of the animation software and yet here its a big letdown.

**Comment by artisteacher** [comment] 2022-06-27 15:34
I'm curious about how many issues will be fixed just by moving to QT6. 

As far as drawing lag goes, there seem to be a lot of factors. I don't tend to get much lag with my particular setup. However with vector levels I'm careful not to get too sketchy and never "color in" solid areas with the brush. I've found a wired connection is more stable and less laggy when I'm using an iPad as a tablet. A few of my students don't find that responsive enough and do their drawing in Procreate instead.

I would love for drawing in T2D to feel more like drawing in CSP - the brushes are so nice. At least the current drawing experience in T2D is a lot better than it used to be before the mypaint brushes were added. The default brushes were so limiting.

**Comment by ABelliqueux** [comment] 2022-09-04 14:09
Not sure it's the same bug, but trying to edit a selection on a raster layer with a stylus is also painfully slow in Tahoma2d, i.e :

- Select "Selection tool"
- Select part of a raster layer 
- Try resizing it with a stylus
- Slowness 

Not sure it the OP means drawing as in 'GUI rendering' or as in 'line drawing', but even the cursor rendering is laging on vector/smart raster layers in t2d 1.3.

I checked for these issues in OT 1.6 and I they don't occur there. 

Couldn't it be an issue of the stylus movement coordinates data refreshing too often and "spamming" the rendering queue ?

I didnt look at the code so I have no idea how rendering is done in Tahoma, but it feels like something like this is happening.

**Comment by artisteacher** [comment] 2022-09-04 14:19
I think that OT is using a later version of something as part of the building process? This might lead to the difference in performance. The other big difference is being portable vs. installed.

**Comment by ABelliqueux** [comment] 2022-09-04 14:33
I can't reproduce the selection tool slowness in T2D's appimage so you might be right about the influence of the compiler used.

Still issues with cursor lagging on vector/raster layer while using the brush tool though, albeit a tad less than on the compiled version I think.

**Comment by olddesklamp** [comment] 2022-09-10 15:02
I've got this same problem, except if I make stroke long enough it will "catch up" with my cursor and work as normal. Unlike the OP however this doesn't happen to me in OpenToonz.

https://user-images.githubusercontent.com/74428438/189488992-e8ad43c3-0db3-4670-b8d1-d19f0b2377a1.mov

**Comment by josepablo-espinoza** [comment] 2022-09-12 21:44
I have the same issue, I'm not a Tahoma2D user but I experiencing issues with the shape tool under the modes arc and multiarc in Opentooz running on Debian, for my surprise I found PR https://github.com/tahoma2d/tahoma2d/pull/640 that should fix the issue. So I tried those changes on Opentoonz (only those concerning the conditional-compilation directives to fix on Linux and not the doQuit() ) end it with the arc/multiarc issue solved but in turn made the brush+mouse lagging exactly as @pikhosh @olddesklamp clips, after that I proceed to build Tahoma2D latest thinking It was due to missing something else in my changes but nope same lagging issue.

just my grain of salt.

**Comment by manongjohn** [comment] 2022-09-12 23:05
@josepablo-espinoza At the time that PR was introduced, I believe I was still building Linux using QT 5.9. Later that year I changed to using 5.15 due to a forced environment upgrade in Github. Perhaps that fix on the newer version of QT is now causing a side effect on Linux builds.

Will need to revisit that issue/fix and see if it is causing it.

**Comment by josepablo-espinoza** [comment] 2022-09-12 23:22
Thanks @manongjohn I will keep an eye on this thread the geometric tool is an incredibly useful tool. Sadly I'm not knowledgeable enough to further investigate I'm still navigating through the code to make sense of everything... if there is something I can help or test I'll gladly try.

**Comment by erayzesen** [comment] 2022-10-12 20:10
> 

There is the same problem in my linux system. If I use mouse instead of drawing tablet, it doesn't happen. And I tried opentoonz, it works well in there.

**Closed** 2022-11-26 16:46 UTC
Labels: bug
