### ISSUE TITLE
Tahoma2D Crashes when Making A Smart Raster Layer

### ISSUE THREAD

**Issue by Trickster511** [tahoma2d/tahoma2d#620] opened 2021-03-19 20:34 UTC
**Describe the bug**
When ever I make a new Smart Raster Layer, Tahoma2D crashes right then and there, making it impossible to use Smart Raster Layers. This doesn't happen when creating any other type of layer and if I look into the files afterwards, it corrupts the newly created Smart Raster Layer file.

**To Reproduce**
List steps to reproduce the behavior.
1. Make a new Smart Raster Layer and you'll see it crash

**Device Information:**
 - OS: Windows 10
 - Tahoma2D Version: 1.1
 - GPU: Radeon RX 580 Series

**Comment by artisteacher** [comment] 2021-03-20 16:53
I haven't had that issue on macOS. Can you share a crash report?

**Comment by Trickster511** [comment] 2021-03-20 18:26
> I haven't had that issue on macOS. Can you share a crash report?

I can't seem to find the crash report. I followed the file path to find it and I got all the way to cache, after that it's a butch of empty numbered folders. Is there an easier way to find the crash report or am I doing something wrong?

**Comment by manongjohn** [comment] 2021-03-20 19:10
Sorry. That crash report path won't be enabled until version 1.2.

Do you have anti-virus?  Try turning it off temporarily to see if it is blocking additional executables that Tahoma will try to start behind the scenes.  If so, you will need to set Tahoma2D as an exception.

Another thing to check is, go to the Properties tab of the Tahoma2D/tahomastuff folder.  Make sure you it is not Read-Only and in the Securities tab, make sure you see your username in the list with full permissions.

**Comment by Trickster511** [comment] 2021-03-20 20:49
> Sorry. That crash report path won't be enabled until version 1.2.
> 
> Do you have anti-virus? Try turning it off temporarily to see if it is blocking additional executables that Tahoma will try to start behind the scenes. If so, you will need to set Tahoma2D as an exception.
> 
> Another thing to check is, go to the Properties tab of the Tahoma2D/tahomastuff folder. Make sure you it is not Read-Only and in the Securities tab, make sure you see your username in the list with full permissions.

I just tried these, I turned off my anti-virus and even gave Tahoma2D an exception, that didn't work. I even seen my anti-virus's history to see if it blocked anything relating to Tahoma2D, that wasn't the case.

I don't see a properties tab in Tahoma2D's files, I looked in every folder and the closest I found to what you're talking about is profiles > users > *username*. There's also config > permissions, but I don't think that's it?

**Comment by manongjohn** [comment] 2021-03-20 20:55
In Windows Explorer, go to the `Tahoma2D` folder where you unziped and maybe moved it after  the download. It would be whereever you are running Tahoma2D.exe from.

Inside the Tahoma2D folder is a `tahomastuff`. Right-click that and select `Properties` and check the settings.

**Comment by Trickster511** [comment] 2021-03-20 21:59
> In Windows Explorer, go to the `Tahoma2D` folder where you unziped and maybe moved it after the download. It would be whereever you are running Tahoma2D.exe from.
> 
> Inside the Tahoma2D folder is a `tahomastuff`. Right-click that and select `Properties` and check the settings.

Oh! Okay, I got what you mean now. So I did turn off the Read-Only tick box and I pressed apply and ok. It still didn't work and when I right clicked on the tahomastuff folder again, it says the Read-Only tick box is still ticked even though I unticked it, I don't know why it's doing that. I also checked the security tab, my username is in the list and has full permissions

**Comment by manongjohn** [comment] 2021-03-20 22:06
Try moving the entire Tahoma2D folder to your Desktop, or Program Files or main C: directory and see if location of where you extracted it to might be an issue.

**Comment by Trickster511** [comment] 2021-03-21 02:48
> Try moving the entire Tahoma2D folder to your Desktop, or Program Files or main C: directory and see if location of where you extracted it to might be an issue.

Yeah I tried putting it everywhere and still the same results. I'll just downgrade to 1.0 and hope the next update fixes this issue, but thanks for helping

**Comment by DarrenTAnims** [comment] 2021-03-21 11:38
Unless we know what the issue is, it won't be fixed. This works for other users, so there's something about your system that must be different. If you have any more details that could help, please share them here. Otherwise it's likely this issue will be closed at some point.

**Comment by Trickster511** [comment] 2021-03-21 14:30
> Unless we know what the issue is, it won't be fixed. This works for other users, so there's something about your system that must be different. If you have any more details that could help, please share them here. Otherwise it's likely this issue will be closed at some point.

I see. In that case, I'll try to give as much info as I can.

This issue only happened on the 1.1 version of Tahoma, and I didn't do anything different from the last version as far as install location, so I figure it was a bug with the version. But now that I know I'm the only one with this issue, maybe it's my computer doing something to the program. I have a AMD Radeon Graphics Processor and a Radeon RX 580 Series graphics card. My antivirus is Norton and I allowed permissions for Tahoma2D

As far as the bug itself, as soon as I press OK or Apply when making a Smart Raster Layer, a second later, the program closes itself and that's it. When I open the program back up, I can still access the layer I made, however any drawings I make onto it doesn't persist when I save and in fact shows an error when saving. The layer also has a palette of light blue colors for some reason. The exact error that pops up is "Can not save the following resources: 'name of layer'" followed by another popup "An error occurred while saving, Please check your work and try again."

If there's anymore info you need, ask and I'll try to provide, and again thanks for helping me with this

**Comment by manongjohn** [comment] 2021-03-21 14:53
Still sounds like its having issues working in the tahomastuff folder.

Are you using the sandbox project or a project outside of sandbox? If using the sandbox project,  can you create a project folder elsewhere on your machine and try creating your assets and scenes there.

**Comment by Trickster511** [comment] 2021-03-21 15:19
> Still sounds like its having issues working in the tahomastuff folder.
> 
> Are you using the sandbox project or a project outside of sandbox? If using the sandbox project, can you create a project folder elsewhere on your machine and try creating your assets and scenes there.

I tried that, I put the project in documents outside the tahomastuff folder and I made another project and put it on the desktop, same issue

**Comment by manongjohn** [comment] 2021-03-21 15:30
Ok..try the following...just to see if one of the other executables Tahoma2D uses is giving you problems:

1. Open a command prompt 
2. cd to wherever you put the Tahoma2D folder
3. Try and run the following executables without arguments
- lzocompress.exe
- lzodecompress.exe
- tcomposer.exe

**Comment by Trickster511** [comment] 2021-03-21 15:50
> Ok..try the following...just to see if one of the other executables Tahoma2D uses is giving you problems:
> 
> 1. Open a command prompt
> 2. cd to wherever you put the Tahoma2D folder
> 3. Try and run the following executables without arguments
> 
> * lzocompress.exe
> * lzodecompress.exe
> * tcomposer.exe

Oh interesting! I don't have the Izocompress.exe file in the Tahoma2D folder, could that be the issue?

**Comment by manongjohn** [comment] 2021-03-21 15:56
Yes. Its possible your antivirus quarantined it.

**Comment by Trickster511** [comment] 2021-03-21 16:43
> Yes. Its possible your antivirus quarantined it.

That was it! I took the file out of quarantine, excluded it from any future scans, tested it and it works now! Thanks so much for the help :D

**Closed** 2021-03-24 20:07 UTC
Labels: bug
